### ISSUE TITLE
'add category' button vanishes

### ISSUE THREAD

**Issue by Le-Barbu** [HenriDellal/emerald#13]
After adding a certain number of categories, the 'add category' button shrinks, then disappeares. The whole screen has to be filled up by category entries for this to happen.

**Comment by HenriDellal** [comment]
Thanks for reporting, I'll upload the fix now.

**Comment by qwertyuser1983** [comment]
This issue still persist, in the latest FDroid Installer, 0.5.0.1, sorry Henry. :)

**Comment by HenriDellal** [comment]
There are some troubles with F-Droid updates at this moment. 0.5.0.1 is outdated. It was fixed with this commit:
https://github.com/HenriDellal/emerald/commit/9907bcdb33f70e28b7ca846cd4a5115a29e7c2a1
Please update to 0.5.1.1 through Github or Play Store.

**Comment by qwertyuser1983** [comment]
Thanks.

Working normally now. :)
