### ISSUE TITLE
unclassified apps unlisted after first launch

### ISSUE THREAD

**Issue by Le-Barbu** [HenriDellal/emerald#14]
Launching an app from the 'unclassified' category gives them the 'history' category and removes them from the 'unclassified' category.

**Comment by HenriDellal** [comment]
It wasn't considered as a bad behaviour, since "history" is just another category to classify, but it seems very reasonable to make changes, so it will be done.

**Comment by Le-Barbu** [comment]
I thought it was weird to auto remove it since there's no automation whatsoever. I see the logic now although from a user's point of view it seems very unnatural to skim through the 'unclassified' category only to find that its content was moved to an unknown place. Keep up the good work.
