### ISSUE TITLE
App is not updated on F-Droid

### ISSUE THREAD

**Issue by FliegendeWurst** [HenriDellal/emerald#16]
It is currently two versions behind :(

**Comment by HenriDellal** [comment]
I have to rely on F-Droid Bot, because I have no ability to update the app myself at this moment. Apologies for that.

**Comment by HenriDellal** [comment]
I have run into a problem with F-Droid update. It was planned to be compiled by F-Droid from the source code, but it seems like it didn't work. So, I've decided to make an .apk on the dedicated server using bash script with instructions. It will take some time to prepare all the things needed.

**Comment by HenriDellal** [comment]
I have probably found the reason of update failure. The targetSdk version must be changed to 26 (Oreo).

**Comment by FliegendeWurst** [comment]
It's fixed now! :tada:
