### ISSUE TITLE
Dock bar or favourite apps

### ISSUE THREAD

**Issue by HenriDellal** [HenriDellal/emerald#3]
I don't know which features it should have. I'd say the most needed are:

- Background color preference;
- Support unlimited number of apps in dock and make it scrollable if they don't fit the width;
- Hide dock when searching.

The other option is to show the favourite apps after pressing the menu button(both on-screen and device), that is similar to KISS Launcher circle behaviour.

**Comment by volnes** [comment]
+1 for that
