### ISSUE TITLE
"All" and "Unclassified" categories are confused

### ISSUE THREAD

**Issue by xxxxme** [HenriDellal/emerald#34]
I have classified a number of apps into various user-created categories and set the Unclassified category as home. With previous versions of Emerald as well as 0.5.2.4, sometimes when pressing the home button from inside an app, the All category will be shown with the Unclassified label. I will not be able to see only Unclassified apps until I switch to another category besides Unclassified or All then back. This persists through the setting Home Button Behavior > Don't Switch.
(Samsung T399 w/ CyanogenMod 12-20150319, Android 5.0.2)

**Comment by HenriDellal** [comment]
Hello. Thanks for reporting, it was fixed with the latest commit.
