### ISSUE TITLE
Cannot add apps to categories from last update

### ISSUE THREAD

**Issue by qwertyuser1983** [HenriDellal/emerald#35]
From long press menu, I tried to move all my app away from unfinished to appropriate categories.

From the last update, it just stop working. :(

Advan i5E. FDroid

**Comment by HenriDellal** [comment]
Hello. I've found this bug in 0.5.2.3 and now it's fixed with the latest commit. You can use category manager to move apps until the next update.

**Comment by qwertyuser1983** [comment]
Thanks! This fast! :)
