### ISSUE TITLE
Launcher crash on Storage permission question

### ISSUE THREAD

**Issue by heycrip** [HenriDellal/emerald#41]
When selecting either "Backup Preferences" or "Restore Preferences" for the first time, launcher crashes and a permission request is displayed, followed by a crash notification on top.

Can be recreated by denying Storage permission and selecting either Backup or Restore Preferences.

![screenshot_20180113-094632_package installer](https://user-images.githubusercontent.com/12774050/34904963-30e167fe-f850-11e7-8a69-d40d4e84d34f.jpg)
![screenshot_20180113-095056_package installer](https://user-images.githubusercontent.com/12774050/34904964-31078ed4-f850-11e7-8f1b-3027c0681146.jpg)

**Comment by HenriDellal** [comment]
It was fixed recently. Both Google Play and F-Droid don't have a fixed version yet.

**Comment by heycrip** [comment]
Oh, cool. 
Just tested it in a local build and indeed this now works.
