### ISSUE TITLE
Protect apps unstallations

### ISSUE THREAD

**Issue by flavi1** [HenriDellal/emerald#42]
Hello.

Possibility to add a password to protect apps removing. There's already apps to protect apps access. For example if i protect app store and parameters access against uninstaller access, then it doesn't make sence if i'm able to do it without restriction from the launcher.

Thanks ;)

**Comment by HenriDellal** [comment]
Hello.
It's a good idea. I will implement it. The only thing I should mention is that the launcher doesn't save its password in a safe way at this moment.

**Comment by flavi1** [comment]
Assuming traditional user can't by pass the launcher to use phone,
i understand this is not now your priority to save password in safe way.
Thank you ;)

2018-01-17 14:23 GMT+01:00 HenriDellal <notifications@github.com>:
