### ISSUE TITLE
Swipe to navigate between categories

### ISSUE THREAD

**Issue by flavi1** [HenriDellal/emerald#43]
Realy not important, but should be great...

**Comment by HenriDellal** [comment]
It's possible to make swipes on the category name, but it's not very accurate. As for the window swipe, it is most likely to not be implemented.

**Comment by flavi1** [comment]
Not important, just a little cosmetic and superficial idea ;)

2018-01-17 14:28 GMT+01:00 HenriDellal <notifications@github.com>:
