### ISSUE TITLE
Enable fast scroll / scroll bar

### ISSUE THREAD

**Issue by thomasaiman** [HenriDellal/emerald#44]
Be able to drag your finger along the right side of the screen to quickly scroll through the list.
![kmh1q](https://user-images.githubusercontent.com/32423251/35077415-d8547844-fbc2-11e7-8e83-02d07d7be3b7.png)

**Comment by HenriDellal** [comment]
Hello.
Thanks for your suggestion. This is to be implemented. The code already has some parts of it that are commented. I didn't manage to make fast scroll and letter hint to work together though.
