### ISSUE TITLE
Theme selection can't reset to original look

### ISSUE THREAD

**Issue by protectivedad** [HenriDellal/emerald#46]
The Theme selection with a new install has no radial button selected. Selecting one will change the theme but there is no way to get back to the "Original" theme without reseting the apps data.

**Comment by HenriDellal** [comment]
Hello.
I can't reproduce it, please write your Android version and post the preferences backup without any theme selected(if possible). Thanks.

**Comment by protectivedad** [comment]
It's ICS (4.0.3) and I've attached the preferences file with no theme selected. I don't think restoring the preferences file works either.

[preferences.txt](https://github.com/HenriDellal/emerald/files/1662092/preferences.txt)

**Comment by HenriDellal** [comment]
Thanks. As I see from the file, it has Light theme chosen just as I expected it to be. The strange thing is that it doesn't show the selection properly. Please tell what doesn't work in restoring.

**Comment by protectivedad** [comment]
When I first went to restore after I reset the apps data, nothing was restored that I could see. Neither landscape or portrait prefs, Looking a little closer, the "Home button behaviour" was restored. Later when I was trying something different I noticed that it restored some of the prefs. But only the ones that I had changed since the data reset. For example if reset the data and restore the prefs nothing changes. If I change portrait icon size to 52 (from default 48) then restore the prefs (from above) my portrait icon size is restored to 72. I noticed that saving the prefs after a reset only saves a few items I'm guessing those will get restored, but the ones not listed will not. Also is it supposed to save categories?

Back to the theme, selecting LIght theme, turns the icon screen background solid white with black lettering. The menu "..." is transparent background with white lettering. The category selection is transparent background with black lettering.

Selecting Dark theme, turns the icon screen background transparent with white lettering. The menu "..." is transparent background with black lettering. The category selection is transparent background with white lettering.

**Comment by HenriDellal** [comment]
Thank you for such detailed reply. I will fix it soon.

**Comment by HenriDellal** [comment]
Oh, forgot to say that it doesn't save categories at this moment.

**Comment by HenriDellal** [comment]
Well, the restoring was fixed, but theming wasn't. I've moved Holo theme on Lollipop to try it and it seems to work just fine. Probably I will have to check it on pre-Kitkat.

**Comment by HenriDellal** [comment]
Forgot that I've already fixed it. Anyway, there may still be some theming issues.
