### ISSUE TITLE
Duplicate Categories after Reboot

### ISSUE THREAD

**Issue by joe-batt** [HenriDellal/emerald#50]
When I reboot my phone, all phone, all categories are shown twice both in settings and the selector. They are not actually duplicated (entries are identical, deleting a category deletes the duplicate as well) , they just seem to be added to the list twice. Restarting the launcher solves the issue.

**Comment by HenriDellal** [comment]
Hello. Thanks for reporting, I'll try to fix it.

**Comment by xxxxme** [comment]
For me, this only happens with the user-created categories.
