### ISSUE TITLE
Make scroll bar/fast scroll optional via settings

### ISSUE THREAD

**Issue by joe-batt** [HenriDellal/emerald#52]
Maybe I'm just clumsy, but when I try to access apps on the right column I tend to miss the app and fast scroll somewhere else.

**Comment by HenriDellal** [comment]
It's already possible. This option is called "Show letter hint on scroll". Probably, this name is misleading. I can make the additional margin for scroll box also.

**Comment by joe-batt** [comment]
sorry for the late reply. You're right, everything is back to normal when I change that.
