### ISSUE TITLE
Main bar hidden under home touch buttons

### ISSUE THREAD

**Issue by herbertjones** [HenriDellal/emerald#54]
I've only seen this on a phone, which happens to be Android 5.1.1.

When the "main bar" is at the bottom, touching the "main bar" menu causes the "main bar" to drop below the "home touch" buttons so that the menu button of 3 dots, nor the categories bar can be pressed.  Restarting emerald fixes the problem until the "main bar" menu button is touched (something else may trigger this problem also I believe, though I'm not sure of the exact circumstances).  Normally the "main bar" sits above the "home touch" bar until this bug is triggered.

This behavior also occurs when the main bar is at top, but is less noticeable as it only can be seen if there are enough icons to fill the screen, or if icons are positioned starting from the bottom (by the option "Stick category content to the bottom").  When triggered, icons will be hidden behind the "home touch" bar (scrolling all the way up leaves a row of icons behind the "home touch" bar).

**Comment by herbertjones** [comment]
![6726549055420592020](https://user-images.githubusercontent.com/370919/36521741-114c0fde-175e-11e8-898b-8d15c7cc0b3b.png)
![6896900697976289569](https://user-images.githubusercontent.com/370919/36521742-116376b0-175e-11e8-80cc-9465e044345a.png)

**Comment by HenriDellal** [comment]
Hello. Thanks for such detailed report. Sadly I can't test it, because I have only phones with hardware buttons. I will try to fix it, but I need someone to test the solution. Please could you help me?

**Comment by herbertjones** [comment]
Yeah, I should be able to.  Thanks!

**Comment by HenriDellal** [comment]
@herbertjones, please could you check the latest version (0.5.5) for this bug?
