### ISSUE TITLE
Enter key does not launch application

### ISSUE THREAD

**Issue by go2null** [HenriDellal/emerald#56]
When using a physical keyboard, I can navigate with the arrow keys to an app icon.  However, when I press ENTER, the icon "blinks" but the app doesn't launch.

Emerald Launcher v0.5.4 from F-Droid on Samsung Galaxy Tab S2

**Comment by go2null** [comment]
reference: https://github.com/seizonsenryaku/HayaiLauncher/issues/12

**Comment by HenriDellal** [comment]
Hello.
Thanks for reporting and especially for referencing, that's very helpful. I'll try to fix it. Please tell us if you have any ideas regarding keyboard usage and tablet/TV interface.

**Comment by HenriDellal** [comment]
https://github.com/seizonsenryaku/HayaiLauncher/commit/8bafbab4506f44975129467cff6d7481024bc000

**Comment by go2null** [comment]
Thanks for your quick response on this.

> Please tell us if you have any ideas regarding keyboard usage and tablet/TV interface.

Guess that ensuring that a UI is navigatable with a keyboard would be sufficient.  This should cover dpads and controllers as they emulate/extend keyboard support.

Better support would be to support accessibility.

For example, TAB should jump between UI elements; ARROW KEYS should navigate lists.

Further Info:  https://developer.android.com/training/keyboard-input/navigation.html

**Comment by HenriDellal** [comment]
I've added physical keyboard support in 0.5.6. Please could you test it when it is on F-Droid?
How to use
Press any Meta key(Ctrl, Alt) and then press one of the following:
0 for search;
1..9 for apps in dock (at this moment it's not possible to add more than 5 icons to dock though);
Enter or Dpad center key to launch an app;
Left/Right to switch categories.
