### ISSUE TITLE
Emerald Launcher does not respect device orientation

### ISSUE THREAD

**Issue by go2null** [HenriDellal/emerald#57]
With default settings, the Launcher starts in Portrait mode, even when the device is in Landscape orientation.  This is sub-optimal on a phone/tablet, but is much more problematic on an Android TV box.

Emerald Launcher v0.5.4 from F-Droid on Samsung Galaxy Tab S2

**Comment by go2null** [comment]
On my Galaxy Tab S2, I cannot access the Settings - pressing the menu icon (3 vertical dots) does nothing.  To be clear, this is using the tablet's touchscreen, not a keyboard.

**Comment by HenriDellal** [comment]
I'll change the default configuration then. As for Settings bug, I don't know why it happens, but I'll look into it.

**Comment by go2null** [comment]
Not fixed.

Tested with v0.5.6 from F-Droid on
- Samsung Galaxy Tab S2 (Android 7.0) with  Screen Rotation set to *Auto-Rotate* and *Landscape*, and
- Google Pixel (Android 8.1.0) with *Auto-Rotate*.

**Comment by go2null** [comment]
v0.5.6.2 from F-Droid **NOT** fixed on Pixel with Android 8.1.0.
