### ISSUE TITLE
Apps list to scroll horizontally

### ISSUE THREAD

**Issue by jaxkodex** [HenriDellal/emerald#59]
Hello, 

Great app! I was wondering if there is an option to scroll the App list horizontally or if there should be? I didn't find it on the settings.

**Comment by HenriDellal** [comment]
Hello. Thank you for the kind words. There is no option to make the app list scroll horizontally and it is most likely to not be implemented. Anyway, as this app is open source, you may edit it that way so it will work. I may help you with that.

**Comment by jaxkodex** [comment]
Oh, ok, So i'd like do that mod :), could you please help me out to import the project and stuff? I couldn't get the project running, was hopping for gradle and stuff

**Comment by HenriDellal** [comment]
We don't use gradle, because it is too complicated for such project. To compile Emerald you have to use build-emerald.sh script. You should check the path to Android SDK ($BASE and $SDK) in it and change it if needed.

**Comment by HenriDellal** [comment]
You can replace the GridView (represents the app list) with [TwoWayGridView](https://github.com/jess-anders/two-way-gridview), [HorizontalGridView](https://developer.android.com/reference/android/support/v17/leanback/widget/HorizontalGridView.html) or even your custom view.
