### ISSUE TITLE
No more fast scrolling in 0.5.6

### ISSUE THREAD

**Issue by sprnza** [HenriDellal/emerald#60]
Hi there! Was it removed intentionally or it's regress?
Bigger category name looks much better BTW!
Thank you for efforts to make this great app!

**Comment by HenriDellal** [comment]
Hello. Thanks for the feedback.
It wasn't removed and it works for me. Probably the preference value wasn't saved, so you should enable it manually from the settings.

**Comment by sprnza** [comment]
Don't see anything regarding this in the settings. Maybe I'm wrong with terminology. I mean he feature when you swipe category name to get next one selected. Doesn't work on two phones with Andr4.4 and 6.1

**Comment by HenriDellal** [comment]
It was disabled for some time. I'm going to introduce switching through swipe on apps grid soon.
