### ISSUE TITLE
Crash when tapping main bar category name

### ISSUE THREAD

**Issue by thomasaiman** [HenriDellal/emerald#63]
Instant crash when tapping the category name (e.g. "All Apps"). The search button and the menu button (three dots) still work fine. This is new for me in v0.5.6.

Motorola G5 Plus
Android 7.0

**Comment by HenriDellal** [comment]
Hello.
Thanks for the report. This bug is known and it was fixed in 0.5.6.1. F-Droid haven't built this version yet, so we have to wait some days.

**Comment by thomasaiman** [comment]
Just installed v0.5.6.1 and you are right it's fixed.
