### ISSUE TITLE
font style not working for all applications

### ISSUE THREAD

**Issue by dgamee** [HenriDellal/emerald#67]
#### Expected behavior
I was expecting all my application names to be bold and also be in italic 

#### Actual behavior
After selecting my font style to be bold and italic some of the application font style didnt change.

#### How to reproduce
* Download emerald launcher
* click the three vertical dot button 
* Select Launcher settings
* Click appearance preferences 
* Scroll down and select font style
* choose bold and italic 
<p>

* App Version: 0.5.6.1
* Operating system: Android 7.0
* Device Used: Infinix Hot 5
#### Recording Of The Bug

https://s31.postimg.org/wmt98vr0r/emerald.png
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@lordrayden/font-style-not-working-for-all-applications">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by HenriDellal** [comment]
Hello.
Thanks for reporting. It happens because after change you have to restart the launcher. I'll fix it but for now you can restart launcher manually from launcher preferences.
