### ISSUE TITLE
some icons can't be loaded

### ISSUE THREAD

**Issue by vn971** [HenriDellal/emerald#7]
Some applications do not have a proper icon, like on this screenshot:
![screenshot_emerald-20171011-124707](https://user-images.githubusercontent.com/1547617/31437355-abc7edd8-ae8d-11e7-9bdd-417fe6c24787.png)

On my device, the following apps have icon missing: AnySoftKeyboard, Contacts, Firefox Klar, PDF Viewer, Settings. All other apps are drawn correctly. Anything specific about these apps?

P.S. Thank you for your work! I've already replaced "Hayai" launcher with Emerald, which seems to be an improvement.:)

**Comment by vn971** [comment]
Offtopic: I don't know where to put it, but if you may be interested, I see the following pros and cons in the current version of emerald:
* the "dark" Theme just makes font color black, and doesn't change anything else. Background is always black. So with a "dark" theme you just don't see captions, and that's it. I guess the "light" theme is meant to have a light background color?
* when you press `...` (app settings), the pop-up appears on the buttom, not near of the place where you pressed
* the restarting process is a bit confusing, especially since I moved through the settings from "up" to "buttom", and saw the "restart" option only at the last step. All previous times I had to try reloading the app in some wierd manner, and it didn't always work. Maybe put the "restart" action on the top?.. IDK.
* Having easily switchable "history" and "alphabetical" mode is nice.
* maybe reduce the default "font size" at least a bit? I've set mine to `3`, initially it was _extremely_ large, especially if you enable both icon and text.
* it's a bit confusing to see "Font Style" setting, but no "Font Size" setting nearby. I thought it's just non-existent and though to leave a feedback and revert to my old launcher until I finally found it under orientation-specefic settings. Maybe move "font size" closer to "font style"? IDK, it may be a personal mistake.
* as an alternative to "column width", it would be cool to just select the number of apps you want to fit on each row. Simpler to understand, yet as customizeable as it was.
* something to consider, I'm not sure myself, but can we re-structure "portrait"/"landscape" preferences? For example, move all the settings like "Font Size" outside in the main list, but when a user clicks "Font Size", they see a window with 3 items: "portrait font size" (value), checkbox "override landscape for mode" and, if the checkbox is enabled, "landscape font size" (value). Just something to consider.
* rename "App shortcut" to "Show as" maybe?
* IDK what "grid" checkbox does exactly. If you disable it, the list just becomes hellish.
* one of the most important things, it feels like `emerald` somehow doesn't cache app list view. If I scroll down fast, it lags a bit. Like it's re-calculating the view. "KISS" and "Hayai" never lag, IIRC.

This feedback is meant to just be feedback, not criticism in any way. Thanks for your work!

**Comment by HenriDellal** [comment]
Hello, @vn971 . Great thanks for your feedback, that's very helpful. The icons may be wrong if you're using a custom icon pack(issue #6 ). You can help by sending a backup of launcher settings(before the restart option).

Themes are to change the color of text and default icons(search, settings, etc). It changes the background only for pre-Holo androids.

The launcher's context menu is the thing that I was thinking about. Haven't implemented it yet because of low importance.

Restart option will be moved up.

Switching "history" and "alphabetical" can be done by setting History as home category. Then you can switch between them by pressing Home button. You can also swipe left or right on the spinner to switch categories.

The number of columns is the option that I'm feeling like to implement.

Disabling of the grid option makes the GridView looking like a list. You have to restart the launcher to see changes, didn't mention that.

I'm not aware of how the view caching works by default, so I have to dig in it to say something.

Other notes will be considered as well.

**Comment by vn971** [comment]
@HenriDellal, Thanks. Regarding icon pack -- I think I'm using the default one. When I open "Appearance" > Icon pack, I only see one item "Default", and it's selected. Note that I use CopperheadOS, which doesn't have Google services built-in. (IDK if it matters.)

Yes, since you can just switch between "history" and "alphabetical" by a simple "Home" press, it becomes very convenient to do so. I like this feature a lot.:)

Indeed, restarting worked. Cool.:) (Though I like the grid more, since it's implemented, of course.:)

I'm not sure exactly what kind of caching it is myself. As I approximately measured, emerald freezes (a bit) when I move about 2 screens from top to bottom. It's always reproducable on my phone.

**Comment by vn971** [comment]
Sorry, even though I use a default icon set, maybe you meant to share the preferences. No problem: https://gist.github.com/vn971/8e1175c85b129a5591f91d04fcabe593

Some other feedback:
* save app preferences as "emerald-preferences.txt"

**Comment by HenriDellal** [comment]
Yes, this is what I've meant exactly. That's very strange. There is nothing specific about these apps and the launcher doesn't depend on gapps, so I'm wondering what is the reason for such behaviour. Maybe you should try to refresh the app list manually by pressing Menu button > Full scan.

**Comment by vn971** [comment]
@HenriDellal I did it multiple times, that's the strange part. And it's always the same apps that are working incorrectly. Other info that might be useful:
* it's always the same apps that somewhy have icon broken
* it works in "Hayai launcher" and "Launcher3"
* the android version is 8.0 (nexus 6p "angler")
* IIRC, "Contacts" app and "Settings" app changed their icon when upgraded to android 8.0. Maybe the new Android version allows using some new format for icons, like SVG?

**Comment by HenriDellal** [comment]
This may be related to adaptive icons introduced in Oreo. The same bug was found on Google Pixel.

**Comment by vn971** [comment]
On a fresh Android 9, it looks like that...
![Screenshot_20190508-232236_Emerald_Launcher](https://user-images.githubusercontent.com/1547617/57409527-cd2adb00-71e8-11e9-8ed6-88385ae6e41c.png)

**Comment by BeatLink** [comment]
I have the same issue here. This is the only thing stopping me from using this app

**Comment by MicrosoftTakeover** [comment]
Currently experiencing this same issue with certain devices. It happens on Android 8 but not on Android 5.

**Comment by HenriDellal** [comment]
I have to say that I managed to fix this bug, the update will be uploaded soon.

**Comment by vn971** [comment]
@HenriDellal  Whoaaaaa, awesome! Will you make a release for it to be picked up by F-Droid?

**Comment by HenriDellal** [comment]
IIRC it's autopicked, I created a release with v1.0 tag, so it should work.

**Comment by vn971** [comment]
Confirming it's fixed, thanks!
