### ISSUE TITLE
Request to do copywriting.

### ISSUE THREAD

**Issue by kodeblacc** [HenriDellal/emerald#72]
I'll love to do copywriting on your project which includes reordering your readme file, about us, FAQs and privacy policy. These will give more insight of your project to other people.I anticipate your response.

**Comment by HenriDellal** [comment]
Hello.
I'd like to hear your suggestions on readme. Also, you can help with pull request/issue templates. As for the other things, I think that they're not needed.
Thanks.

**Comment by HenriDellal** [comment]
Hello.
I'd like to hear your suggestions on readme. Also, you can help with pull request/issue templates. As for the other things, I think that they're not needed.
Thanks.

**Comment by kodeblacc** [comment]
Okay, I'll work on the readme right away.

**Comment by kodeblacc** [comment]
Hello, I just made a pr for the readme file I proposed. You can check it
out.

Thanks
