### ISSUE TITLE
[Q] widgets

### ISSUE THREAD

**Issue by ildar** [HenriDellal/emerald#77]
Widgets are immaculate for many launchers. Whether widgets will be supported or not it should be written​ in Readme IMHO. Thanks

**Comment by HenriDellal** [comment]
Hello.
The launcher is most likely not to introduce widgets in future updates. Thanks for the idea, I'll mention it in readme. Also, it is possible to use Emerald as app drawer with other launchers. I would recommend EcoHome for that, but there are other options as well (KLWP+Null launcher, etc).
