### ISSUE TITLE
Migrate to Android Studio?

### ISSUE THREAD

**Issue by FliegendeWurst** [HenriDellal/emerald#81]
Currently, I first have to import the project into Android Studio. You can read more here: https://android-developers.googleblog.com/2015/06/an-update-on-eclipse-android-developer.html

**Comment by HenriDellal** [comment]
Since it should be helpful for contributors, I think that it will be done. I can't do it at this moment though, have to prepare an update first.

**Comment by FliegendeWurst** [comment]
I can open a PR in a week or so, if that's ok for you.
