### ISSUE TITLE
Can we pin apps on home screen

### ISSUE THREAD

**Issue by hapishyguy** [HenriDellal/emerald#99]
Can we pin only 2 or 3 or 4 apps only on the home acreen so that when the device is factory reset and boot back up those apps on the home screen remain the same.

**Comment by HenriDellal** [comment]
Hello.
Sorry, I can't understand the question. Please could you elaborate the question?

**Comment by hapishyguy** [comment]
I figured :).
eg. I have set youtube, netflix another app on the home page. Now when I factory reset the device these 3 apps will be gone. I have to again set these apps on the home screen. Is there any feature, since its open source, that after we favtory reset the box those 3 apps stay there so that we dont have to manually add them. 
I think its not possible as it is, unless I or someone else fork this or otherwise customize it for themselves.
Also, I tried it on an andrpid box with the remote. It dont work with the remote. Is it also possible to make it work with the remote.

**Comment by FliegendeWurst** [comment]
So you want the launcher to automatically install other apps? I don't think that's possible for any launcher.

**Comment by HenriDellal** [comment]
It's not possible to backup and restore categories' content now, but it's planned (#51). Though Emerald won't be able to reinstall apps after factory reset. There should be other apps for such task. As for TV box support, feel free to create new issue with description of expected behaviour. Thanks.
